version: '3.2'
services:
  db:
    container_name: 'database'
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always


volumes:
  db: